cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "stable"

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Has been set in travis-ci.org dashboard; secure
  keep-history: true
  local_dir: dist
  on:
    branch: develop
